### ISSUE TITLE
Add @dev comment explaining .decimals() behavior? 

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#167]
@Namaskar-1F64F https://youtu.be/L8dijE5qhTg?t=1618 Joey talks about what happens on `.decimals()`call if it's not implemented. If there is a fallback implemented on the contract it would call that instead

_Originally posted by @RusseII in https://github.com/porter-finance/v1-core/issues/80#issuecomment-1079587047_

**Comment by Namaskar-1F64F** [comment]
Could do - but what's actionable there? As far as I understand any of those external calls will result in a call to the `fallback` function. If there are no decimals we've already lost the goat and if the fallback returns a `uint8` between 0 and 18 the contract will carry on, but we cannot differentiate that being returned by a call to `decimals` or not.

**Comment by RusseII** [comment]
> Could do - but what's actionable there?

I thought it may be useful to auditors / people reading the code to understand what happens in the case of .decimals() not being implemented. Please close this issue if you do not agree.
