### ISSUE TITLE
Gnosis Auction Allow-List

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#172]
# Current Auction Allow-List Process 

1. The DAO specifies a signer address of who they would like to manage the allow-list
2. The DAO creates the gnosis auction passing in that addresses
3. Someone who has the PK for that signer address does `git clone https://github.com/gnosis/ido-contracts`
4. `yarn` 
5. The owner of the signer address creates a file `your_address_inputs.txt` with comma separated addresses that should be allow-listed for the auction
6. They run 
```bash
export NETWORK=<Your Network>
export INFURA_KEY=<Your infura key>
export PK=<Your private key _for the signing address_. The address for this key should not hold any ETH>
yarn hardhat generateSignatures --auction-id "Your auctionId" --file-with-address "./your_address_inputs.txt" --network $NETWORK --post-to-api
```

This could be done at any time to add to add new address to the allow-list. Not sure if addresses are able to be removed after being added.

# Next Steps
I would advocate for sticking with the current process for launch & exploring ways to make the allow-listing process more intuitive post-launch. 
We could also handle the key generation for DAOs if they were comfortable using a signing address that we own, and giving us their allow-list.  

@jordanalexandermeyer lmk if you think this should be a priority sooner. 

_Originally posted by @RusseII in https://github.com/porter-finance/v1-core/issues/38#issuecomment-1083637828_

**Comment by jordanalexandermeyer** [comment]
How are those signatures used to allow a lender to bid?

Gnosis Auction documentation mentions they are served via the Gnosis Auction UI: "The signed messages for the users can be created by running this [generateSignatures](https://github.com/gnosis/ido-contracts#allow-listing-generating-signatures) hardhat-script by referencing the list of allow-listed addresses. It should be run with the additional argument post-to-api, such that the signatures are uploaded to the GnosisDAO backend. From there, Gnosis Auction will serve the signatures automatically to users once they connect to the UI."

https://gnosis-auction.eth.link/#/docs/private-auctions-and-KYC-solutions

**Comment by RusseII** [comment]
> How are those signatures used to allow a lender to bid?

On their frontend - we call gnosis API to see if a signature is stored. If it is stored, we show them the bid UI. If it is not stored, we show them the private auction UI. 

On the transaction side the Gnosis contract checks if the address was added to the allow list
<img width="490" alt="image" src="https://user-images.githubusercontent.com/15036618/161307496-003babe5-8da2-40dc-989d-b3c11e736c89.png">
