### ISSUE TITLE
Change `bondCreated` parameters 

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#195]
In the current implementation I'm concerned about using the collateral ratio and convertible ratio when creating the bond due to the complexity in calculating them #168. 

Some DAOs will be creating the transaction themselves and a mistake in the collateral or convertible ratio would be a costly mistake. 

I propose changing the inputs from `collateralRatio,  convertibleRatio, maxBonds` to `collateralAmount,  convertibleAmount, bonds` and we calculate the ratios in the `bondCreated` call.

**Comment by RusseII** [comment]
@jordanalexandermeyer thoughts?

**Comment by jordanalexandermeyer** [comment]
Agreed. How about `collateralTokenAmount` and `convertibleTokenAmount`?
