### ISSUE TITLE
Divide by Zero errors? 

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#198]
We are dividing by `totalSupply` in multiple places in our contracts. Will that cause errors/issues when there is a totalsupply of 0? (after all bonds are redeemed or burned)

**Comment by Namaskar-1F64F** [comment]
No. The only place division by totalSupply (or division at all) is in `previewRedeemAtMaturity`. If there are in fact 0 bonds at this point, the redeem would fail.

**Comment by RusseII** [comment]
> No. The only place division by totalSupply (or division at all) is in previewRedeemAtMaturity. If there are in fact 0 bonds at this point, the redeem would fail.

From [4626](https://eips.ethereum.org/EIPS/eip-4626#previewredeem)
> MUST NOT revert due to vault specific user/global limits. MAY revert due to other conditions that would also cause redeem to revert.

I think I would like to handle this similar to how [rari does](https://github.com/Rari-Capital/solmate/blob/e802bcf2fb24dda2bf7e513bea86d15c48b57486/src/mixins/ERC4626.sol#L127), it seems weird to me that the transaction will revert in the case of a previewRedeem call after all bonds have been burned/claimed due to dividing by zero

**Comment by RusseII** [comment]
https://github.com/ethereum/solidity/pull/888 I think this does throw on divide by 0 .... probably fine .... @Pet3ris do you think we should check for this case explicitly? Or save the gas and let the transaction revert automatically on 0

**Comment by RusseII** [comment]
<img width="1914" alt="image" src="https://user-images.githubusercontent.com/15036618/163257567-51f01f31-e190-47b6-89be-607dabe2216f.png">

The error is bad on divide by zero revert

**Comment by Pet3ris** [comment]
I'd personally favor checking explicitly for the benefit of future previews but reverts are fine too with sufficient clarity on the front-end.
