### ISSUE TITLE
1. **Missing sanity/threshold checks in input validation**

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#201]
1. **Summary**:_ _Sanity/threshold checks (depending on their types) on input parameters are missing. 
    2. **Details**:  Sanity/threshold checks are missing on `_maturityDate`, `_collateralRatio`, `_convertibleRatio` and `_maxSupply` of the `intialize` function.
    3. **Github Permalinks**: <code>[initialize](https://github.com/porter-finance/v1-core/blob/CAREX/contracts/Bond.sol#L219-L248)</code>
    4. <strong>Mitigation</strong>: Perform appropriate sanity/threshold checks (depending on their types) on input parameters. For example, <code>_maxSupply</code> could be 0 checked and upper bounded.

**Comment by RusseII** [comment]
@jordanalexandermeyer 
1. What should the minimum maturity date for a bond be? (1 week?, 1 month?) 
1. What should the max issuance amount be? (100m? 500m? 1b?) 
1. Should the `collateralToken` and the `paymentToken` be allowed to be the same token? WETH for both for example? 
1. Is there a floor amount of bonds that we would want to require to be minted? Or should we just check that (bonds > 0) (1k floor? 10k floor? 50k floor?)

**Comment by jordanalexandermeyer** [comment]
@RusseII 
1. Maturity date should be in the future
2. Do we need a max supply? These contracts could technically be used for non-USD borrow tokens.
3. There's no reason to disallow them being the same token unless it makes the contracts more complicated. Currently, if the `paymentToken` is the same as the `collateralToken`, would the bond be considered "repaid" at issuance. For example there are 500 USDC in the contract and 100 USDC are owed.
4. I think (bonds > 0) is fine.

**Comment by RusseII** [comment]
@jordanalexandermeyer to clarify - the reasoning for adding these checks would to be to help protect issuers from accidentally entering an invalid configuration. Honestly - if they have a bad config it wouldn't be the end of the world because they should always be able to burn all of the bonds and withdraw all of the collateral. 

1. There was some pre-audit feedback: 
> Lower limit on maturity is unclear
Summary: There is lack of clarity about the minimum maturity of a bond.
Details: The [initialize](https://github.com/porter-finance/v1-core/blob/fef9b407a03684c88c926b420944549cdafa418d/contracts/Bond.sol#L233-L235) function checks for block.timestamp as the lower limit and block.timestamp + 3650 days as the upper limit. It has to be considered how practical it is to have a bond that lasts only a few seconds or minutes, and what kind of impact that may have on the overall protocol. This documentation and any enforcement on the minimum maturity period of bonds is missing.
Github Permalinks: initialize 
Mitigation: Consider adding checks for minimum maturity period of bonds. This should be clarified in the specification and documentation.

We can ignore this advice if you think it makes sense. We may want to consider blocking auctioning off matured bonds via our frontend. 
2. We don't need a max supply. Having one would help prevent accidentally entering an extra 0 though if we knew what upper bound was reasonable. 
3. It doesn't make them more complicated. It'd just help protect against an invalid config
4. Sounds good


No need to respond to this issue unless you have further thoughts. Your above answer was sufficient.

**Comment by jordanalexandermeyer** [comment]
3. It doesn't make them more complicated. It'd just help protect against an invalid config

Would the bond be considered "repaid" if they put up 200 USDC as collateral and borrowed 100 USDC?

**Comment by jordanalexandermeyer** [comment]
Agreed. Let's disallow it.
