### ISSUE TITLE
8. Time-delayed change of critical parameter is absent

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#207]
8. **Time-delayed change of critical parameter is absent**
    29. **Summary**: Change of critical parameters should be emitted via events and enforced only after a time delay.
    30. **Details**: When critical parameters of systems need to be changed, it is required to broadcast the change via event emission and recommended to enforce the changes after a time-delay. This is to allow system users to be aware of such critical changes and give them an opportunity to exit or adjust their engagement with the system accordingly. 

   isAllowListEnabled, when toggled to false via setIsAllowListEnabled, would open up the system to issuers without ISSUER_ROLE.  This significantly and immediately changes the trust & threat model of the system for the users.

    All access-controlled functions that set/change critical addresses/parameters in these contracts should apply a timelock.

    31. **Github Permalinks**: [setIsAllowListEnabled](https://github.com/porter-finance/v1-core/blob/CAREX/contracts/BondFactory.sol#L77-L88)
    32. **Mitigation**: Critical protocol updates should happen only after an adequate time delay so users have time to react. If not, this should be clearly documented and communicated to all users as a potential risk.

**Comment by RusseII** [comment]
If we want to implement this, Peteris recommended doing this inline ourselves. 

For example, we create a new variable (comesIntoAffect) and check if currentTimestamp > comesIntoAffect

We can talk with the auditors about if they think this is necessary or not, or if having an insta-switch is fine.

**Comment by Namaskar-1F64F** [comment]
related to #236

**Comment by RusseII** [comment]
Zellic thought this was not necessary. We should just make this clear in our docs - and let users know in advance of us changing this.
