### ISSUE TITLE
12. **The logic contract can be claimed and initialised by anyone**

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#210]
12. **The logic contract can be claimed and initialised by anyone**
    45. **Summary**: tokenImplementation logic contract can be claimed and initialised by anyone.
    46. **Details**: While this has no effect on the clone contracts (which is what tokenImplementation is used for), the logic contract should ideally not be claimed and initialised by anyone to prevent any unforeseen interactions. 
    47. **Github Permalinks**: [BondFactory.constructor](https://github.com/porter-finance/v1-core/blob/CAREX/contracts/BondFactory.sol#L69-L75)
    48. **Mitigation**: tokenImplementation logic contract could be claimed and initialised by calling its initialize method with dummy values in BondFactory.constructor.

**Comment by Namaskar-1F64F** [comment]
closing in favor of adding to the deployment script instead of modifying the contracts #240
