### ISSUE TITLE
25. Lower limit on maturity is unclear

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#214]
25. **Lower limit on maturity is unclear**
    97. **Summary**: There is lack of clarity about the minimum maturity of a bond.
    98. **Details**: The initialize function checks for block.timestamp as the lower limit and block.timestamp + 3650 days as the upper limit. It has to be considered how practical it is to have a bond that lasts only a few seconds or minutes, and what kind of impact that may have on the overall protocol. This documentation and any enforcement on the minimum maturity period of bonds is missing.
    99. **Github Permalinks**: [initialize](https://github.com/porter-finance/v1-core/blob/fef9b407a03684c88c926b420944549cdafa418d/contracts/Bond.sol#L233-L235) 
    100. **Mitigation**: Consider adding checks for minimum maturity period of bonds. This should be clarified in the specification and documentation.

**Comment by Namaskar-1F64F** [comment]
do we want to remove the 10 year check?

**Comment by RusseII** [comment]
> do we want to remove the 10 year check?

No. The 10 year check is good. See more in #201
