### ISSUE TITLE
34. Gas optimisations by using unchecked blocks

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#219]
34. **Gas optimisations by using unchecked blocks**
    133. **Summary**: Gas optimizations can be achieved by using unchecked blocks for expressions that can be determined not to underflow/overflow.
    134. **Details**: Built-in overflow and underflow checks in Solidity versions >= 0.8.0 cost more gas and can be avoided by using unchecked blocks for expressions that can be determined not to underflow/overflow.
    135. **Github Permalinks**: [previewWithdraw](https://github.com/porter-finance/v1-core/blob/CAREX/contracts/Bond.sol#L518), [_safeTransferIn](https://github.com/porter-finance/v1-core/blob/CAREX/contracts/Bond.sol#L615), [_computeScalingFactor](https://github.com/porter-finance/v1-core/blob/CAREX/contracts/Bond.sol#L635)
    136. **Mitigation**: Use an unchecked block when checks/comparisons for overflow and underflow are already done or are not necessary.

**Comment by Namaskar-1F64F** [comment]
This is one of those changes that feels like it sacrifices readability for marginal gains.

**Comment by RusseII** [comment]
> This is one of those changes that feels like it sacrifices readability for marginal gains.

Sounds good. We removed two of those methods anyway
