### ISSUE TITLE
Emit event during bond factory construction

### ISSUE THREAD

**Issue by Namaskar-1F64F** [porter-finance/v1-core#261]
The state variables `isIssuerAllowListEnabled` and `isTokenAllowListEnabled` emit events when they are toggled throughout the bond factories' existence. During contract deployment the values are initialized to `true`, but this change isn't reflected through the events `IssuerAllowListEnabled` and `TokenAllowListEnabled` which usually signal the change. I propose we add the events to the constructor as such.

```
/*
    When deployed, the deployer will be granted the DEFAULT_ADMIN_ROLE. This
    gives the ability the ability to call `grantRole` to grant access to
    the ISSUER_ROLE as well as the ability to toggle if the allow list
    is enabled or not at any time. The allow list events are emitted as the
    value of the lists "changed" to true during construction.
*/
constructor() {
    tokenImplementation = address(new Bond());
    _grantRole(DEFAULT_ADMIN_ROLE, _msgSender());
    emit IssuerAllowListEnabled(true);
    emit TokenAllowListEnabled(true);
}
```

Also, yes "the ability the ability" is a typo included in the current contract 🖌️

**Comment by RusseII** [comment]
This could go either way. I'd like to not do this based on my thoughts + peteris + auditors. Please re-open if you feel strongly about adding this!
