### ISSUE TITLE
 Make sure your UI links to your GitHub repo.

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#268]
From https://github.com/nascentxyz/nascent-security/blob/main/pre-launch-security-checklist.md 

@jordanalexandermeyer we don't currently have a GH link anywhere in our UI - do we want to add this?

**Comment by jordanalexandermeyer** [comment]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/44010262/166893103-cd062245-eef1-4508-8556-62f5375c7c9f.png">

It's in the lower right corner.

**Comment by RusseII** [comment]
Do we want on landing page as well?

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/15036618/166914288-81a386c9-9c4b-477f-bdf3-04abec6f8998.png">

**Comment by RusseII** [comment]
I see you added this - thanks @jordanalexandermeyer !

**Comment by jordanalexandermeyer** [comment]
Added
