### ISSUE TITLE
consider reentrancy guard usage

### ISSUE THREAD

**Issue by Namaskar-1F64F** [porter-finance/v1-core#275]
https://github.com/spearbit-audits/porter/pull/1/files/9cb5b8ed8d6ba0d95cc4ed8528d23aebbb740890#r863259144

**Comment by RusseII** [comment]
I'm leaning towards adding it as an abundance of caution. I think the only time it'd be an issue though is if we accidentally allow a 777 token in the future. So it'd do nothing in the present but it'd basically be an additional safeguard if there is a problem upstream
