### ISSUE TITLE
Deploy to Mainnet

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#291]
- [x] Deploy to mainnet and verify on etherscan! (Both implementation contract and factory)
- [x] Transfer ownership of bondFactory to Gnosis Safe then use Gnosis safe to revoke the admin role from the deployment address

@Namaskar-1F64F let's plan to do this together on a call :) Will be fun

**Comment by Namaskar-1F64F** [comment]
Deployed contract:
https://etherscan.io/address/0x778e0bf89a5f3cac5333a0613691390d41f35227

Revoke role transaction through gnosis safe:
https://etherscan.io/tx/0x8f6c7e206a5f42895d599b99ca0fc026bc3820b7c2286ec5bb932d966f03c21b
