### ISSUE TITLE
Should we be using paymentBalance more places? 

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#296]
We have a function 
```
   function paymentBalance() public view returns (uint256 paymentTokens) {
        paymentTokens = IERC20Metadata(paymentToken).balanceOf(address(this));
    }
  ```
  
  Yet we call `IERC20Metadata(paymentToken).balanceOf(address(this))` 4 additional places in our contract. Why? Shouldn't we just be calling the `paymentBalance()` function in each of those places?
* https://github.com/porter-finance/v1-core/blob/c15332210b00fa7fc98c490bd7615d59dbae15a0/contracts/Bond.sol#L282
* https://github.com/porter-finance/v1-core/blob/c15332210b00fa7fc98c490bd7615d59dbae15a0/contracts/Bond.sol#L295
* https://github.com/porter-finance/v1-core/blob/c15332210b00fa7fc98c490bd7615d59dbae15a0/contracts/Bond.sol#L158
* https://github.com/porter-finance/v1-core/blob/c15332210b00fa7fc98c490bd7615d59dbae15a0/contracts/Bond.sol#L166

Note: 
If we make this change - we need to be very sure that it works correctly or payment tokens could be swept from the contract https://github.com/porter-finance/v1-core/blob/c15332210b00fa7fc98c490bd7615d59dbae15a0/contracts/Bond.sol#L300

Note2: 
Same question for collateralBalance: https://github.com/porter-finance/v1-core/blob/c15332210b00fa7fc98c490bd7615d59dbae15a0/contracts/Bond.sol#L284

**Comment by Namaskar-1F64F** [comment]
Yes these would be better as `paymentBalance` and `collateralBalance`. I don't think we should make this change as it's purely cosmetic and I do not want to change the contracts much past what's deployed/audited.
