### ISSUE TITLE
Volt Code Review Takeaways 

### ISSUE THREAD

**Issue by RusseII** [porter-finance/v1-core#298]
- [x] Add assert test for GRACE_PERIOD
- [x] #297 
- [ ] @ElliotFriedman to check if there is a way for us to easily reduce contract size with regular factory
- [x] Make it more clear of the 1:1 relationship between bonds and the payment token at maturity. Bonds will be sold at a discount. (Make sure to do this in our docs updates)
- [x] #319
- [x] Consider copy pasting NatSpec 
- [x] Think about adding more inline comments
- [x] https://github.com/porter-finance/v1-core/issues/294)
- [x] #295 
- [x] #299

**Comment by ElliotFriedman** [comment]
to expand on the assert test for GRACE_PERIOD, all state variables that get set in a constructor or during initialization need to be tested for correctness

**Comment by RusseII** [comment]
> Or maybe it was if it was possible at all. I think @RusseII might have run into trouble deploying at all with the size of our contracts + imports.

I think the issue was if we did not use the clone factory then the contract size was too large for us to deploy. I think @ElliotFriedman had some issue like this in the past and was going to see if it was possible to deploy the bondFactory + bond code separately to reduce contract size with a regular factory?

**Comment by ElliotFriedman** [comment]
It really should be possible. Try running hardhat contract size on your contracts in their current state, then try doing another run of the contract size after you remove the creation of a new bond token in the factory. The factory bytecode should be smaller after you remove the creation of the new token.

**Comment by Namaskar-1F64F** [comment]
After removing the bond and the instantiation, 

```diff
- import "./Bond.sol";
```

```diff
- tokenImplementation = address(new Bond());
+ tokenImplementation = address(0x0);
```
<img width="537" alt="CleanShot 2022-06-13 at 19 45 50@2x" src="https://user-images.githubusercontent.com/7458951/173413337-1a6ba95a-a5cc-48ae-8ced-2b01fa86715d.png">

**Comment by ElliotFriedman** [comment]
Nice!
