### ISSUE TITLE
Improve token math

### ISSUE THREAD

**Issue by Namaskar-1F64F** [porter-finance/v1-core#80]
Meeting with peteris tomorrow - will fill this out with more information. 
https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/WeightedPool.sol

**Comment by RusseII** [comment]
@Namaskar-1F64F https://youtu.be/L8dijE5qhTg?t=1618 Joey talks about what happens on `.decimals()`call if it's not implemented. If there is a fallback implemented on the contract it would call that instead
